import { Routes, Route, useLocation, useNavigate } from 'react-router-dom';
import { useState, useEffect } from 'react';

export default function ArticleDetail() {
  const { state } = useLocation();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (state?.url) {
      fetch(`http://127.0.0.1:8000/article-detail?url=${encodeURIComponent(state.url)}`)
        .then((r) => r.json())
        .then((d) => {
          setData(d);
          setLoading(false);
        })
        .catch(() => setLoading(false));
    } else {
      setLoading(false);
    }
  }, [state?.url]);

  if (!state)
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-gray-600">
        <p className="mb-4 text-lg">No article selected. Go back to the list.</p>
        <button
          onClick={() => navigate('/')}
          className="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition"
        >
          Back to Feed
        </button>
      </div>
    );

  if (loading)
    return (
      <div className="flex justify-center items-center h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-t-4 border-blue-600"></div>
      </div>
    );

  return (
    <div className="max-w-7xl mx-auto p-6 mt-4 grid grid-cols-1 lg:grid-cols-3 gap-8">
      {/* Left Column - Article */}
      <div className="lg:col-span-2 bg-white rounded-xl shadow-md border border-gray-100 p-6">
        <h1 className="text-2xl font-bold text-gray-900 mb-3 leading-snug">
          {state.title}
        </h1>
        <p className="text-sm text-gray-500 mb-6">
          Source: <span className="font-semibold text-gray-700">{state.source}</span> •{' '}
          {new Date(state.publishedAt).toLocaleString()}
        </p>

        {/* Article Body */}
        <div
          className="prose max-w-none text-gray-800 leading-relaxed"
          dangerouslySetInnerHTML={{
            __html:
              data?.highlighted || data?.text || '<p>No article content available.</p>',
          }}
        />

        {/* AI Quiz CTA */}
        <div className="mt-10 text-center border-t border-gray-200 pt-6">
          <h3 className="text-lg font-semibold text-gray-800 mb-2">
            🎯 Test your understanding
          </h3>
          <p className="text-gray-600 mb-4">
            Take a short quiz generated by our AI to earn points and improve your streak!
          </p>
          <button
            onClick={() => navigate('/article/quiz', { state: { article: state } })}
            className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white px-5 py-2 rounded-lg font-medium hover:from-blue-700 hover:to-indigo-700 transition"
          >
            Take Quiz & Earn Points 🧠
          </button>
        </div>
      </div>

      {/* Right Column - Bias Sidebar */}
      <div className="bg-white rounded-xl shadow-md border border-gray-100 p-6 h-fit sticky top-24">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          Top Detected Biases 🧠
        </h2>

        {!data?.biases?.length ? (
          <p className="text-gray-600">
            No strong biases detected. Article appears balanced.
          </p>
        ) : (
          <div className="space-y-4">
            {data.biases.map((b, i) => (
              <div
                key={i}
                className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition bg-gray-50"
              >
                <h3 className="text-blue-600 font-semibold mb-1">
                  #{i + 1} {b.type}
                </h3>
                <p className="text-gray-700 italic text-sm mb-2">“{b.example}”</p>
                <div className="text-sm font-medium text-gray-800">
                  Intensity:{' '}
                  <span className="text-orange-600">
                    {(b.score * 100).toFixed(0)}%
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
